version: "3.8"

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: [ "start", "--log", "debug", "--user", "root", "--pass", "root", "--allow-all", "memory" ]
    ports:
      - "8000:8000"
    volumes:
      - surrealdb_data:/var/lib/surrealdb

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  surrealdb_data:
  qdrant_data: